---
classes:
 - 'profile::base'

ntp::servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org

world: >
    ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEw
    DQYJKoZIhvcNAQEBBQAEggEAopGoqwfABVOXDL/DMV2dEIy5RDF6lcM4wz/c
    Vl7nGSam6JliFPHs2/6DaEHPqexLs4UwasosaOUJiMvKxLnyD+3DaCshu4Wm
    1F2DxRHxtWSi+SnnDyisu6xxUz36GsDpdjPL7Ea43m2yDickxKsen2RN5A2C
    Zqrftitxs5hS2GaN6JWDTlpEl2FFdRoT50rptoey7gkxbNBBLM5u7MiCeFgX
    1YC3km0/E0LvhrOUqxaX8AqMHu7EYJi6Ggj/6Zi1ZNrQuiFzuTw/1dobsDOA
    kGN4NbpF9LRDpjJmqkWKhScHs9nDYb8X3deJlHOAxarvXOHzgUqQI5YQF6yF
    qzst/zBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBruvSyHHYgNYez6sQG
    yMNggCCwALrXUqG4aYGvvIWkEqP1mn22ZtyYENqjcrwF2xEIHg==]
